#pragma config(Motor, port1, Direita, tmotorVex393_HBridge, openLoop, reversed, driveRight)
#pragma config(Motor, port6, Garra, tmotorVex393_MC29, openLoop)
#pragma config(Motor, port7, Braco, tmotorVex393_MC29, openLoop)
#pragma config(Motor, port10, Esquerda, tmotorVex393_HBridge, openLoop, reversed, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true)
	{
		motor[Direita] = (vexRT(Ch3) - vexRT(Ch1)) / 2;
		motor[Esquerda] = (vexRT(Ch3) + vexRT(Ch1)) / 2;

		if (vexRT(Btn5U))
		{
			motor[Braco] = -90;
		}
		else
		{
			motor[Braco] = 0;
		}

		if (vexRT(Btn5D))
		{
			motor[Braco] = 127;
		}
		else
		{
			motor[Braco] = 0;

			if (vexRT(Btn6U))
			{
				motor[Garra] = 127;
			}
			else
			{
				motor[Garra] = 0;
			}

			if (vexRT(Btn6D))
			{
				motor[Garra] = -90;
			}
			else
			{
				motor[Garra] = 0;
			}
		}
	}
}
